# ref: https://www.serverless.com/framework/docs/guides/compose
services:
  anything-auth:
    path: packages/infra/auth
    params:
      distributionDomainName: ${anything-web.distributionDomainName}
      httpApiRootArn: ${anything.httpApiRootArn}
    dependsOn:
      - anything-web
      - anything
  anything:
    path: packages/api
    params:
      streamArn: ${anything-data.streamArn}
    dependsOn:
      - anything-data
  anything-data:
    path: packages/infra/data
    params:
      loggingBucket: ${anything-web.loggingBucket}
    dependsOn:
      - anything-web
  anything-web:
    path: packages/infra/web
