# ref: https://www.serverless.com/framework/docs/guides/compose
# sls (service_name:)deploy
# sls (service_name:)remove
# sls refresh-outputs
#
# Important: To add a new param dependency without having to redeploy 
#  everything, add the param in the providing package and re-deploy first.
#  Then, add the new serverless package in compose below.
#  Or else compose will fail to let you deploy changes to those packages.
# ref: https://github.com/serverless/compose/issues/148
services:
  anything-database:
    path: packages/infra/database
  anything:
    path: packages/api
#    params:
#      distributionDomainName: ${anything-web.distributionDomainName}
#    dependsOn:
#      - anything-web
  anything-web:
    path: packages/infra/web
    params:
      apiDomainName: ${anything.apiDomainName}
    dependsOn:
      - anything
  anything-auth:
    path: packages/infra/auth
    params:
      distributionDomainName: ${anything-web.distributionDomainName}
      apiRootArn: ${anything.apiRootArn}
    dependsOn:
      - anything
      - anything-web
  anything-data:
    path: packages/infra/data
    params:
      loggingBucket: ${anything-web.loggingBucket}
      streamArn: ${anything-database.streamArn}
      streamTableName: ${anything-database.streamTableName}
    dependsOn:
      - anything-web
      - anything-database
  anything-dash:
    path: packages/infra/dash
    params:
      dataBucketArn: ${anything-data.dataBucketArn}
      queryResultsBucketArn: ${anything-data.queryResultsBucketArn}
      glueDatabase: ${anything-data.glueDatabase}
      glueMainTable: ${anything-data.glueMainTable}
      athenaWorkgroup: ${anything-data.athenaWorkgroup}
    dependsOn:
      - anything-data
