# ref: https://www.serverless.com/framework/docs/guides/compose
# sls (service_name:)deploy
# sls (service_name:)remove
# sls refresh-outputs
services:
  anything-database:
    path: packages/infra/database
  anything:
    path: packages/api
#    params:
#      distributionDomainName: ${anything-web.distributionDomainName}
#    dependsOn:
#      - anything-web
  anything-web:
    path: packages/infra/web
    params:
      apiDomainName: ${anything.apiDomainName}
    dependsOn:
      - anything
  anything-auth:
    path: packages/infra/auth
    params:
      distributionDomainName: ${anything-web.distributionDomainName}
      apiRootArn: ${anything.apiRootArn}
    dependsOn:
      - anything
      - anything-web
  anything-data:
    path: packages/infra/data
    params:
      loggingBucket: ${anything-web.loggingBucket}
      streamArn: ${anything-database.streamArn}
      streamTableName: ${anything-database.streamTableName}
    dependsOn:
      - anything-web
      - anything-database
