# ref: https://www.serverless.com/framework/docs/guides/compose
services:
  anything:
    path: packages/api
    params:
      streamArn: ${anything-data.streamArn}
    dependsOn:
      - anything-data
  anything-auth:
    path: packages/infra/auth
    params:
      distributionDomainName: ${anything-data.distributionDomainName}
      httpApiRootArn: ${anything.httpApiRootArn}
    dependsOn:
      - anything-data
      - anything
  anything-data:
    path: packages/infra/data