# ref: https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml
service: anything
frameworkVersion: "3"
configValidationMode: warn
# Plugin order matters
plugins:
  - serverless-better-credentials  # first
  # Choose one of: plugin-typescript, esbuild
#  - serverless-plugin-typescript
  - serverless-esbuild
  - serverless-dynamodb
  - serverless-offline  # last
custom:
  tscpaths:
    tsconfigPath: tsconfig.json
  # ref: https://www.serverless.com/plugins/serverless-esbuild
  esbuild:
    bundle: true
    minify: false
    watch:
      pattern: './**/*.(js|ts)'
      ignore: ['./__tests__/**/*', './**/*.test.ts']  # OK
  # ref: https://www.serverless.com/plugins/serverless-offline
  serverless-offline:
    httpPort: ${env:API_PORT, 4000}
    websocketPort: ${env:WEBSOCKET_PORT, 4001}
    lambdaPort: ${env:LAMBDA_PORT, 4002}
    # If JWT auth is used, offline plugin can't actually validate JWT signature and throws errors
    # ref: https://www.serverless.com/plugins/serverless-offline#jwt-authorizers
    ignoreJWTSignature: true
    # Offline plugin has issues with IAM auth, only supports JWT auth
    # ref: https://github.com/dherault/serverless-offline/issues/1311
    noAuth: true
    noPrependStateInUrl: true
  # ref: https://www.npmjs.com/package/serverless-dynamodb
  #serverless-dynamodb:
  dynamodb:
    stages:
      - dev
    start:
      # To bring up dynamodb yourself with docker compose, uncomment below.
      #  Otherwise, serverless plugin will start up the local dynamodb.
      #noStart: true
      # sharedDb settings makes dynamodb use one common db file,
      #  which allows us to use any AWS profile (access keys) for development.
      sharedDb: true
      host: localhost
      port: 5000
      # dbPath is relative to: <projectroot>/node_modules/serverless-dynamodb
      dbPath: '../../docker/dynamodb'
      migrate: true
      heapInitial: 200m
      heapMax: 1g
      convertEmptyValues: true
      migration: true
      seed: true
      #cors: '*'
      #docker: true
      #inMemory: true
    migration:
      dir: './src/migrations'
      host: localhost
    seed:
      test:
        sources:
          - table: ${self:provider.environment.NAMESPACE}-main
            sources: [./src/data/testData.json]
          - table: ${self:provider.environment.NAMESPACE}-types
            sources: [./src/data/testDataTypes.json]
functions:
  - ${file(./src/modules/item/item.functions.yml)}
  - ${file(./src/modules/collection/collection.functions.yml)}
  - ${file(./src/modules/type/type.functions.yml)}
  - ${file(./src/modules/health/health.functions.yml)}
provider: ${file(./_provider.yml)}  # OK
resources:
  # Array of files each with Resources object
  # ref: https://www.serverless.com/framework/docs/providers/aws/guide/variables#multiple-configuration-files
  #- ${file(_resources.yml)}
  - Outputs:
      # Pass HTTP API endpoint to the auth resources so they know what to auth
      httpApiRootArn:
        Value: !Sub 'arn:aws:execute-api:${env:AWS_REGION}:${AWS::AccountId}:${HttpApi}'
      httpApiDomainName:
        Value: !Sub '${HttpApi}.execute-api.${env:AWS_REGION}.amazonaws.com'
